#!/bin/bash

# uninstall desktop launcher
xdg-desktop-menu uninstall /opt/translationstudio/unfoldingword-translationstudio.desktop

# uninstall icon
xdg-icon-resource uninstall --size 128 unfoldingword-translationstudio
xdg-icon-resource uninstall --size 64 unfoldingword-translationstudio
xdg-icon-resource uninstall --size 48 unfoldingword-translationstudio
xdg-icon-resource uninstall --size 32 unfoldingword-translationstudio
xdg-icon-resource uninstall --size 22 unfoldingword-translationstudio
xdg-icon-resource uninstall --size 16 unfoldingword-translationstudio
